<a href="https://colab.research.google.com/github/OctavioQuinter3/Programacion_maestria/blob/main/Practica4_266226.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Datos de alumno

Estudiante: Octavio Quintero Flores

Matricula: 266226

Maestría en Inteligencia Artificial y Analítica de Datos

# Instrucciones de la actividad

Crea dos matrices de 3x3 con números aleatorios entre 1 y 10. Realiza las siguientes operaciones:

Suma ambas matrices.

Resta la segunda matriz de la primera.

Multiplica la primera matriz por 2.

Realiza una multiplicación matricial entre las dos matrices.

#Inicio de codigo

In [1]:
import numpy as np

Importamos la libreria a utilizar, en este caso Numpy para el manejo de matrices.

In [4]:
matriz_a = np.random.randint(1, 11,(3, 3))
matriz_b = np.random.randint(1, 11,(3, 3))

print("Matriz A:")
print(matriz_a)
print("\nMatriz B:")
print(matriz_b)

Matriz A:
[[7 6 1]
 [5 4 8]
 [9 7 2]]

Matriz B:
[[4 7 1]
 [5 5 9]
 [6 4 9]]


Creamos nuestra matriz a y b, utilizamos lo siguiente

```Python
np.random.randint(1, 11,(3, 3))
```
donde random.randint para la creacion de numeros random enteros donde (1,11) es el valor minimo y 11 es el valor maximo quitandole 1 siendo 10 y (3, 3) el tamaño de la matriz

#Suma de matrices

In [5]:
suma = matriz_a + matriz_b
print("Suma de matrices:")
print(suma)

Suma de matrices:
[[11 13  2]
 [10  9 17]
 [15 11 11]]


#Resta de segunda matriz a primera

In [6]:
resta = matriz_a - matriz_b
print("Resta de matrices:")
print(resta)

Resta de matrices:
[[ 3 -1  0]
 [ 0 -1 -1]
 [ 3  3 -7]]


#Multiplicacion por 2 a matriz A

In [7]:
multiplicacion = matriz_a * 2
print("Multiplicacion por 2 de matriz A:")
print(multiplicacion)

Multiplicacion por 2 de matriz A:
[[14 12  2]
 [10  8 16]
 [18 14  4]]


Como vimos en este caso es la multiplicaion escalar, a continuacion realizaremos la multiplicacion de matricial que utiliza .dot para realizarlo.

In [9]:
producto_matricial = np.dot(matriz_a, matriz_b)
print("Producto matricial de las matrices:")
print(producto_matricial)

Producto matricial de las matrices:
[[ 64  83  70]
 [ 88  87 113]
 [ 83 106  90]]


#Conclusion

En esta actividad pude hacer uso de numpy para el manejo de matrices, podemos observar la rapidez con la cual se puede desarrollar gracias al uso de Numpy.